services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./media:/app/media
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/web/node_modules
    command: bun --watch run apps/api/src/index.ts
    depends_on:
      - redis
    networks:
      - app_network
  redis:
    image: redis:latest
    container_name: redis-server
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app_network
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    restart: always
    networks:
      - app_network

  bull-board:
    image: venatum/bull-board:latest
    container_name: bullmq_dashboard
    ports:
      - "3002:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BULL_VERSION=BULLMQ
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
